apiVersion: apps/v1
kind: Deployment

metadata:
  name: proyecto-devops-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: proyecto-devops

  template:
    metadata:
      labels:
        app: proyecto-devops

    spec:
      containers:
        - name: proyecto-devops

          image: proyecto-devops:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 5000