name: Docker Kubernetes Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # DOCKER
      # -------------------------
      - name: Build Docker Image
        run: docker build -t mi-app .

      - name: Ejecutar contenedor
        run: docker run mi-app

      # -------------------------
      # INSTALL KUBECTL
      # -------------------------
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # -------------------------
      # INSTALL KIND (KUBERNETES LOCAL EN CI)
      # -------------------------
      - name: Install KIND
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Create Kubernetes Cluster
        run: kind create cluster

      # -------------------------
      # KUBERNETES DEPLOY
      # -------------------------
      - name: Kubernetes Deployment
        run: kubectl apply -f deployment.yml

      - name: Kubernetes Service
        run: kubectl apply -f service.yml
      - name: Ver recursos
        run: kubectl get pods