name: Docker Kubernetes Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mi-app .

      - name: Ejecutar contenedor
        run: docker run mi-app

      - name: Kubernetes Deployment
        run: kubectl apply -f deployment.yml

      - name: Kubernetes Service
        run: kubectl apply -f service.yml